name = "gallai_c2_formalization"
version = "0.1.0"

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "c55e6e786f49471c72fbddbec5415808896aec1e"

[[lean_lib]]
name = "Gallai"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "ReleaseAudit"
